### ISSUE TITLE
empty antenna table

### ISSUE THREAD

**Issue by rvweeren** [jurjen93/lofar_helpers#1]
H.root.sol000.antenna[:]['name'] is empty 

(H.root.sol000.phase/amplitude000.ant are ok)

Solution, maybe just copy H.root.sol000.phase over to H.root.sol000.antenna[:]['name'] ?

**Comment by jurjen93** [comment]
Thanks! I fixed it by first of all do a check if all antennas from the to-merge h5 files are the same (and in the same order). In the end, I copy the antennas from one of the to-merge h5 files to the new output file.
