### ISSUE TITLE
missing polarization axis while merging tables with equal dimensions

### ISSUE THREAD

**Issue by ggurkan** [jurjen93/lofar_helpers#13]
While merging solutions tables with the same number of axes the code does not check whether the pol axis is available and crashes, an example of traceback:
File "lofar_helpers/h5_merger.py", line 2007, in merge_h5
    merge.upsample_weights()
  File "/h5_merger.py", line 1400, in upsample_weights
    pol_index = axes_new.index('pol')
ValueError: 'pol' is not in list

**Comment by jurjen93** [comment]
Hi @ggurkan , thank you for notifying this issue. I added an extra `elif` in case there is no 'pol' such as in your case where you have `err000` in your table. It should be fixed now.
