### ISSUE TITLE
h5_merger.py directions get mixed when adding to existing one on Python < 3.6

### ISSUE THREAD

**Issue by tikk3r** [jurjen93/lofar_helpers#3]
Opening this for reference here. Before Python 3.6 dictionary order is not preserved. This trips up the code when dealing with directions that already exist:
https://github.com/jurjen93/lofar_helpers/blob/5c89f9fc80caa20a0d8e682821187a2ca60c1eab/h5_merger.py#L453-L456

I suspect that this implicitely assumes the order of `self.directions` is the same, but since this is not guaranteed for dictionaries, the value `idx` will depend on that order. Three tests seem to confirm this:

- If amplitude is merged first, the amplitude entry is correct but phase is not.
- If phase is merged first, the phase entry is correct, but amplitude is not.
- On Python 3.8 the merge runs fine.

I think potential solutions might be to use an [OrderedDict](https://docs.python.org/3/library/collections.html), which remembers the order in which things were added to it, or to not rely on order at all by using the dictionary keys to find the proper index.

**Comment by jurjen93** [comment]
Thanks for raising this issue and for proposing this solution. OrderedDict is implemented.
