### ISSUE TITLE
h5_merger.py removing international stations

### ISSUE THREAD

**Issue by jwpetley** [jurjen93/lofar_helpers#7]
When using h5_merger.py with the pill-latestNov.simg image and the --add_cs feature, the international stations are removed from the merged .h5 file. We are using a post-prefactor MS which has the core station information but not international while the .h5 inputs are from international self calibration. It would be best if the international information was not removed and just that the core station information could be added. 

Example script:

`python3 h5_merger.py --add_cs -out merged_sols.h5 -in '*.h5' --usesolset 'sol000' -ms <post-prefactor-ms> `

**Comment by jurjen93** [comment]
Hi James,
Thanks for raising this issue. I will resolve it tomorrow morning.

**Comment by jurjen93** [comment]
Hi James,
Thanks for raising this issue. I will resolve it tomorrow morning.
Would you have an example of 1 h5 and the MS file, such that I can properly test it?

**Comment by lmorabit** [comment]
Hi Jurjen -- test data can be grabbed here with wget: 
https://public.spider.surfsara.nl/project/lofarvlbi/screens_wg/testingH5s.tar  (a couple of h5 files)
https://public.spider.surfsara.nl/project/lofarvlbi/screens_wg/TGT1_L665186_SB011_ABN114.tar  (a measurement set, in a subdirectory)

Let me know if you need anything else!

**Comment by jurjen93** [comment]
Should be fixed now. So, you can pull h5_merger.py from the master branch. :)
Let me know if it does now the right thing
